/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema;

/**
 *
 * @author Carla
 */
public class Cinema extends javax.swing.JFrame {

    /**
     * Creates new form Cinema
     */
    public Cinema() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFilm1 = new javax.swing.JPanel();
        jLabelFilmName1 = new javax.swing.JLabel();
        jLabelFilm1 = new javax.swing.JLabel();
        jTextFieldFilmSelector1 = new javax.swing.JTextField();
        jButtonChange1 = new javax.swing.JButton();
        jLabelTotalSales1 = new javax.swing.JLabel();
        jLabelCapacity1 = new javax.swing.JLabel();
        jLabelIncome1 = new javax.swing.JLabel();
        jLabelPrice1 = new javax.swing.JLabel();
        jLabelOccPercentage1 = new javax.swing.JLabel();
        jButtonAddSales1 = new javax.swing.JButton();
        jButtonRemoveSales1 = new javax.swing.JButton();
        jButtonOccupation1 = new javax.swing.JButton();
        jButtonClean1 = new javax.swing.JButton();
        jButtonIncome1 = new javax.swing.JButton();
        jPanelFilm2 = new javax.swing.JPanel();
        jLabelFilmName2 = new javax.swing.JLabel();
        jLabelFilm2 = new javax.swing.JLabel();
        jTextFieldFilmSelector2 = new javax.swing.JTextField();
        jButtonChange2 = new javax.swing.JButton();
        jLabelTotalSales2 = new javax.swing.JLabel();
        jLabelCapacity2 = new javax.swing.JLabel();
        jLabelIncome2 = new javax.swing.JLabel();
        jLabelPrice2 = new javax.swing.JLabel();
        jLabelOccPercentage2 = new javax.swing.JLabel();
        jButtonAddSales2 = new javax.swing.JButton();
        jButtonRemoveSales2 = new javax.swing.JButton();
        jButtonOccupation2 = new javax.swing.JButton();
        jButtonClean2 = new javax.swing.JButton();
        jButtonIncome2 = new javax.swing.JButton();
        jPanelFilm3 = new javax.swing.JPanel();
        jLabelFilmName3 = new javax.swing.JLabel();
        jLabelFilm3 = new javax.swing.JLabel();
        jTextFieldFilmSelector3 = new javax.swing.JTextField();
        jButtonChange3 = new javax.swing.JButton();
        jLabelTotalSales3 = new javax.swing.JLabel();
        jLabelCapacity3 = new javax.swing.JLabel();
        jLabelIncome3 = new javax.swing.JLabel();
        jLabelPrice3 = new javax.swing.JLabel();
        jLabelOccPercentage3 = new javax.swing.JLabel();
        jButtonAddSales3 = new javax.swing.JButton();
        jButtonRemoveSales3 = new javax.swing.JButton();
        jButtonOccupation3 = new javax.swing.JButton();
        jButtonClean3 = new javax.swing.JButton();
        jButtonIncome3 = new javax.swing.JButton();
        jPanelFilm4 = new javax.swing.JPanel();
        jLabelFilmName4 = new javax.swing.JLabel();
        jLabelFilm4 = new javax.swing.JLabel();
        jTextFieldFilmSelector4 = new javax.swing.JTextField();
        jButtonChange4 = new javax.swing.JButton();
        jLabelTotalSales4 = new javax.swing.JLabel();
        jLabelCapacity4 = new javax.swing.JLabel();
        jLabelIncome4 = new javax.swing.JLabel();
        jLabelPrice4 = new javax.swing.JLabel();
        jLabelOccPercentage4 = new javax.swing.JLabel();
        jButtonAddSales4 = new javax.swing.JButton();
        jButtonRemoveSales4 = new javax.swing.JButton();
        jButtonOccupation4 = new javax.swing.JButton();
        jButtonClean4 = new javax.swing.JButton();
        jButtonIncome4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFilm1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanelFilm1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelFilm1.setPreferredSize(new java.awt.Dimension(460, 400));

        jLabelFilmName1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelFilmName1.setText("Film name");

        jLabelFilm1.setText("Película:");

        jButtonChange1.setText("Cambiar");

        jLabelTotalSales1.setText("Total Sales: ");

        jLabelCapacity1.setText("Capacity: ");

        jLabelIncome1.setText("Income: ");

        jLabelPrice1.setText("Price: ");

        jLabelOccPercentage1.setText("Occupation percentage: ");

        jButtonAddSales1.setText("Add Sales");

        jButtonRemoveSales1.setText("Remove sales");

        jButtonOccupation1.setText("% Occupation");

        jButtonClean1.setText("Clean");

        jButtonIncome1.setText("Income");

        javax.swing.GroupLayout jPanelFilm1Layout = new javax.swing.GroupLayout(jPanelFilm1);
        jPanelFilm1.setLayout(jPanelFilm1Layout);
        jPanelFilm1Layout.setHorizontalGroup(
            jPanelFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilm1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilm1Layout.createSequentialGroup()
                        .addGroup(jPanelFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFilmName1)
                            .addGroup(jPanelFilm1Layout.createSequentialGroup()
                                .addComponent(jLabelFilm1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFilmSelector1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonChange1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFilm1Layout.createSequentialGroup()
                        .addGroup(jPanelFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTotalSales1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelIncome1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCapacity1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOccPercentage1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFilm1Layout.createSequentialGroup()
                        .addComponent(jButtonAddSales1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jButtonRemoveSales1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOccupation1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClean1)
                        .addContainerGap(46, Short.MAX_VALUE))))
            .addGroup(jPanelFilm1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jButtonIncome1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelFilm1Layout.setVerticalGroup(
            jPanelFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilm1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabelFilmName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanelFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFilm1)
                    .addComponent(jTextFieldFilmSelector1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChange1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanelFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalSales1)
                    .addComponent(jLabelPrice1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCapacity1)
                    .addComponent(jLabelOccPercentage1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelIncome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanelFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddSales1)
                    .addComponent(jButtonRemoveSales1)
                    .addComponent(jButtonOccupation1)
                    .addComponent(jButtonClean1))
                .addGap(18, 18, 18)
                .addComponent(jButtonIncome1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanelFilm2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanelFilm2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelFilm2.setPreferredSize(new java.awt.Dimension(460, 400));

        jLabelFilmName2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelFilmName2.setText("Film name");

        jLabelFilm2.setText("Película:");

        jButtonChange2.setText("Cambiar");

        jLabelTotalSales2.setText("Total Sales: ");

        jLabelCapacity2.setText("Capacity: ");

        jLabelIncome2.setText("Income: ");

        jLabelPrice2.setText("Price: ");

        jLabelOccPercentage2.setText("Occupation percentage: ");

        jButtonAddSales2.setText("Add Sales");

        jButtonRemoveSales2.setText("Remove sales");

        jButtonOccupation2.setText("% Occupation");

        jButtonClean2.setText("Clean");

        jButtonIncome2.setText("Income");

        javax.swing.GroupLayout jPanelFilm2Layout = new javax.swing.GroupLayout(jPanelFilm2);
        jPanelFilm2.setLayout(jPanelFilm2Layout);
        jPanelFilm2Layout.setHorizontalGroup(
            jPanelFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilm2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilm2Layout.createSequentialGroup()
                        .addGroup(jPanelFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFilmName2)
                            .addGroup(jPanelFilm2Layout.createSequentialGroup()
                                .addComponent(jLabelFilm2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFilmSelector2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonChange2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFilm2Layout.createSequentialGroup()
                        .addGroup(jPanelFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTotalSales2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelIncome2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCapacity2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOccPercentage2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFilm2Layout.createSequentialGroup()
                        .addComponent(jButtonAddSales2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jButtonRemoveSales2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOccupation2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClean2)
                        .addContainerGap(46, Short.MAX_VALUE))))
            .addGroup(jPanelFilm2Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jButtonIncome2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelFilm2Layout.setVerticalGroup(
            jPanelFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilm2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabelFilmName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanelFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFilm2)
                    .addComponent(jTextFieldFilmSelector2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChange2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanelFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalSales2)
                    .addComponent(jLabelPrice2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCapacity2)
                    .addComponent(jLabelOccPercentage2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelIncome2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanelFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddSales2)
                    .addComponent(jButtonRemoveSales2)
                    .addComponent(jButtonOccupation2)
                    .addComponent(jButtonClean2))
                .addGap(18, 18, 18)
                .addComponent(jButtonIncome2)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanelFilm3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanelFilm3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelFilm3.setPreferredSize(new java.awt.Dimension(460, 400));

        jLabelFilmName3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelFilmName3.setText("Film name");

        jLabelFilm3.setText("Película:");

        jButtonChange3.setText("Cambiar");

        jLabelTotalSales3.setText("Total Sales: ");

        jLabelCapacity3.setText("Capacity: ");

        jLabelIncome3.setText("Income: ");

        jLabelPrice3.setText("Price: ");

        jLabelOccPercentage3.setText("Occupation percentage: ");

        jButtonAddSales3.setText("Add Sales");

        jButtonRemoveSales3.setText("Remove sales");

        jButtonOccupation3.setText("% Occupation");

        jButtonClean3.setText("Clean");

        jButtonIncome3.setText("Income");

        javax.swing.GroupLayout jPanelFilm3Layout = new javax.swing.GroupLayout(jPanelFilm3);
        jPanelFilm3.setLayout(jPanelFilm3Layout);
        jPanelFilm3Layout.setHorizontalGroup(
            jPanelFilm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilm3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelFilm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilm3Layout.createSequentialGroup()
                        .addGroup(jPanelFilm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFilmName3)
                            .addGroup(jPanelFilm3Layout.createSequentialGroup()
                                .addComponent(jLabelFilm3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFilmSelector3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonChange3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFilm3Layout.createSequentialGroup()
                        .addGroup(jPanelFilm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTotalSales3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFilm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelIncome3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCapacity3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFilm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOccPercentage3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFilm3Layout.createSequentialGroup()
                        .addComponent(jButtonAddSales3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jButtonRemoveSales3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOccupation3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClean3)
                        .addContainerGap(46, Short.MAX_VALUE))))
            .addGroup(jPanelFilm3Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jButtonIncome3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelFilm3Layout.setVerticalGroup(
            jPanelFilm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilm3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabelFilmName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanelFilm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFilm3)
                    .addComponent(jTextFieldFilmSelector3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChange3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanelFilm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalSales3)
                    .addComponent(jLabelPrice3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFilm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCapacity3)
                    .addComponent(jLabelOccPercentage3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelIncome3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanelFilm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddSales3)
                    .addComponent(jButtonRemoveSales3)
                    .addComponent(jButtonOccupation3)
                    .addComponent(jButtonClean3))
                .addGap(18, 18, 18)
                .addComponent(jButtonIncome3)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanelFilm4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanelFilm4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelFilm4.setPreferredSize(new java.awt.Dimension(460, 400));

        jLabelFilmName4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelFilmName4.setText("Film name");

        jLabelFilm4.setText("Película:");

        jButtonChange4.setText("Cambiar");

        jLabelTotalSales4.setText("Total Sales: ");

        jLabelCapacity4.setText("Capacity: ");

        jLabelIncome4.setText("Income: ");

        jLabelPrice4.setText("Price: ");

        jLabelOccPercentage4.setText("Occupation percentage: ");

        jButtonAddSales4.setText("Add Sales");

        jButtonRemoveSales4.setText("Remove sales");

        jButtonOccupation4.setText("% Occupation");

        jButtonClean4.setText("Clean");

        jButtonIncome4.setText("Income");

        javax.swing.GroupLayout jPanelFilm4Layout = new javax.swing.GroupLayout(jPanelFilm4);
        jPanelFilm4.setLayout(jPanelFilm4Layout);
        jPanelFilm4Layout.setHorizontalGroup(
            jPanelFilm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilm4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelFilm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilm4Layout.createSequentialGroup()
                        .addGroup(jPanelFilm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFilmName4)
                            .addGroup(jPanelFilm4Layout.createSequentialGroup()
                                .addComponent(jLabelFilm4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFilmSelector4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonChange4)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFilm4Layout.createSequentialGroup()
                        .addGroup(jPanelFilm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTotalSales4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFilm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelIncome4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCapacity4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFilm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOccPercentage4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFilm4Layout.createSequentialGroup()
                        .addComponent(jButtonAddSales4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jButtonRemoveSales4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOccupation4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClean4)
                        .addContainerGap(46, Short.MAX_VALUE))))
            .addGroup(jPanelFilm4Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jButtonIncome4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelFilm4Layout.setVerticalGroup(
            jPanelFilm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilm4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabelFilmName4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanelFilm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFilm4)
                    .addComponent(jTextFieldFilmSelector4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChange4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanelFilm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalSales4)
                    .addComponent(jLabelPrice4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFilm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCapacity4)
                    .addComponent(jLabelOccPercentage4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelIncome4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanelFilm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddSales4)
                    .addComponent(jButtonRemoveSales4)
                    .addComponent(jButtonOccupation4)
                    .addComponent(jButtonClean4))
                .addGap(18, 18, 18)
                .addComponent(jButtonIncome4)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelFilm3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelFilm4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelFilm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jPanelFilm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFilm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFilm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelFilm3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFilm4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cinema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cinema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddSales1;
    private javax.swing.JButton jButtonAddSales2;
    private javax.swing.JButton jButtonAddSales3;
    private javax.swing.JButton jButtonAddSales4;
    private javax.swing.JButton jButtonChange1;
    private javax.swing.JButton jButtonChange2;
    private javax.swing.JButton jButtonChange3;
    private javax.swing.JButton jButtonChange4;
    private javax.swing.JButton jButtonClean1;
    private javax.swing.JButton jButtonClean2;
    private javax.swing.JButton jButtonClean3;
    private javax.swing.JButton jButtonClean4;
    private javax.swing.JButton jButtonIncome1;
    private javax.swing.JButton jButtonIncome2;
    private javax.swing.JButton jButtonIncome3;
    private javax.swing.JButton jButtonIncome4;
    private javax.swing.JButton jButtonOccupation1;
    private javax.swing.JButton jButtonOccupation2;
    private javax.swing.JButton jButtonOccupation3;
    private javax.swing.JButton jButtonOccupation4;
    private javax.swing.JButton jButtonRemoveSales1;
    private javax.swing.JButton jButtonRemoveSales2;
    private javax.swing.JButton jButtonRemoveSales3;
    private javax.swing.JButton jButtonRemoveSales4;
    private javax.swing.JLabel jLabelCapacity1;
    private javax.swing.JLabel jLabelCapacity2;
    private javax.swing.JLabel jLabelCapacity3;
    private javax.swing.JLabel jLabelCapacity4;
    private javax.swing.JLabel jLabelFilm1;
    private javax.swing.JLabel jLabelFilm2;
    private javax.swing.JLabel jLabelFilm3;
    private javax.swing.JLabel jLabelFilm4;
    private javax.swing.JLabel jLabelFilmName1;
    private javax.swing.JLabel jLabelFilmName2;
    private javax.swing.JLabel jLabelFilmName3;
    private javax.swing.JLabel jLabelFilmName4;
    private javax.swing.JLabel jLabelIncome1;
    private javax.swing.JLabel jLabelIncome2;
    private javax.swing.JLabel jLabelIncome3;
    private javax.swing.JLabel jLabelIncome4;
    private javax.swing.JLabel jLabelOccPercentage1;
    private javax.swing.JLabel jLabelOccPercentage2;
    private javax.swing.JLabel jLabelOccPercentage3;
    private javax.swing.JLabel jLabelOccPercentage4;
    private javax.swing.JLabel jLabelPrice1;
    private javax.swing.JLabel jLabelPrice2;
    private javax.swing.JLabel jLabelPrice3;
    private javax.swing.JLabel jLabelPrice4;
    private javax.swing.JLabel jLabelTotalSales1;
    private javax.swing.JLabel jLabelTotalSales2;
    private javax.swing.JLabel jLabelTotalSales3;
    private javax.swing.JLabel jLabelTotalSales4;
    private javax.swing.JPanel jPanelFilm1;
    private javax.swing.JPanel jPanelFilm2;
    private javax.swing.JPanel jPanelFilm3;
    private javax.swing.JPanel jPanelFilm4;
    private javax.swing.JTextField jTextFieldFilmSelector1;
    private javax.swing.JTextField jTextFieldFilmSelector2;
    private javax.swing.JTextField jTextFieldFilmSelector3;
    private javax.swing.JTextField jTextFieldFilmSelector4;
    // End of variables declaration//GEN-END:variables
}
